// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZLPEEVgQVXZG1-M5U6iP3etzZSrptOi4',
    appId: '1:674817529988:android:28694f3486666d0ed0cad1',
    messagingSenderId: '674817529988',
    projectId: 'farmers-doorstep',
    storageBucket: 'farmers-doorstep.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtIBj3BI3xwbV1vmggOx8i660WxBT5BJo',
    appId: '1:674817529988:ios:a4005087d6308951d0cad1',
    messagingSenderId: '674817529988',
    projectId: 'farmers-doorstep',
    storageBucket: 'farmers-doorstep.firebasestorage.app',
    androidClientId: '674817529988-5arlp08vrh2kvm914efhnfs8ilr9lsst.apps.googleusercontent.com',
    iosClientId: '674817529988-jcdsfd2jsfb5ukqigk9bseshu6p0nigp.apps.googleusercontent.com',
    iosBundleId: 'com.farmerDoorStep.app',
  );
}
